name: Automatic Web Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
    - run: sed --in-place 's/<LICENSE_KEY>/'${LICENSE_KEY}'/g' ./DentoTools/Program.cs
    - run: dotnet publish ./DentoTools/DentoTools.csproj --configuration Release --output ./output
    - run: sed --in-place 's/<base href="\/"\/>/<base href="\/DentoTools\/"\/>/g' ./output/wwwroot/index.html
    - run: touch ./output/wwwroot/.nojekyll
    - uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: website
        folder: ./output/wwwroot
        single_commit: true
