name: Automatic Web Deploy
on: [push]
env:
  WORKFLOWS_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - run: sed --in-place 's/<LICENSE_KEY>/'${LICENSE_KEY}'/g' ./DentoTools/Program.cs
    - run: dotnet publish ./DentoTools/DentoTools.csproj --configuration Release --output ./output
    - run: sed --in-place 's/<base href="\/"\/>/<base href="\/DentoTools\/"\/>/g' ./output/wwwroot/index.html
    - run: touch ./output/wwwroot/.nojekyll
    - uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${WORKFLOWS_TOKEN}
        BASE_BRANCH: main
        BRANCH: website
        FOLDER: ./output/wwwroot
        SINGLE_COMMIT: true
