name: Quick Publish & Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.X
    - name: Publish
      run: dotnet publish 'CommonToolsOnline/CommonToolsOnline.csproj' --configuration Release --output 'CommonToolsOnline/Output'
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: website
        FOLDER: CommonToolsOnline/Output/wwwroot
        SINGLE_COMMIT: true
